<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE student
[
<!ELEMENT student (enroll,name,mobno,email)>
<!ELEMENT enroll (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT mobno (#PCDATA)>
<!ELEMENT email (#PCDATA)>
]>
<student>
  <student1>
   <enroll>1620bece30183</enroll>	
   <name>Vrushank Amin</name>
   <mobno>9428026763</mobno>
   <email>vrushank796@gmail.com</email>
  </student1> 
  <student2>
   <enroll>1620bece30531</enroll>
   <name>Rahul sharma</name>
   <mobno>9244686313</mobno>
   <email>rahul123@gmail.com</email>
  </student2>
 </student>  

